services:
  - type: web
    name: jobyaari-blog
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: JobYaari Blog
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
      - key: RUN_MIGRATIONS
        value: true
      - key: RUN_SEEDERS
        value: false
